import{a as P,S as q,i}from"./assets/vendor-B5nsgUv9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const E="54641243-abfc91c86f68821b6b62fe46a",$="https://pixabay.com/api/";async function f(t,r=1){const a=new URLSearchParams({key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:15});try{return(await P.get(`${$}?${a}`)).data}catch(o){throw new Error(o.response.status)}}const h=document.querySelector(".gallery"),y=document.querySelector(".loader"),g=document.querySelector(".load-more");let M=new q(".gallery a",{captionsData:"alt",captionDelay:250});function p(t){const r=t.map(({webformatURL:a,largeImageURL:o,tags:e,likes:s,views:n,comments:S,downloads:v})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${o}">
          <img class="gallery-image" src="${a}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${s}</p>
          <p><b>Views:</b> ${n}</p>
          <p><b>Comments:</b> ${S}</p>
          <p><b>Downloads:</b> ${v}</p>
        </div>
      </li>`).join("");h.insertAdjacentHTML("beforeend",r),M.refresh()}function B(){h.innerHTML=""}function b(){y.classList.add("is-visible")}function u(){y.classList.remove("is-visible")}function L(){g.classList.remove("is-hidden")}function d(){g.classList.add("is-hidden")}const O=document.querySelector(".form"),R=document.querySelector(".load-more");let c=1,m="",l=0;const w=15;O.addEventListener("submit",x);R.addEventListener("click",A);async function x(t){t.preventDefault();const r=t.currentTarget,a=r.elements["search-text"].value.trim();if(a===""){i.warning({message:"Please enter a search query!"});return}m=a,c=1,l=0,B(),d(),b();try{const o=await f(m,c);if(o.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),u();return}l=o.totalHits,p(o.hits),l>w&&L()}catch(o){console.error(o),i.error({message:"Something went wrong. Try again later."})}finally{u(),r.reset()}}async function A(){c+=1,d(),b();try{const t=await f(m,c);p(t.hits);const r=Math.ceil(l/w);c>=r?(d(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L(),H()}catch(t){console.error(t),i.error({message:"Error loading more images."})}finally{u()}}function H(){const t=document.querySelector(".gallery-item");if(t){const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
